BROKER_URL = 'librabbitmq://'
CELERY_RESULT_BACKEND = 'amqp'
CELERY_TASK_RESULT_EXPIRES = 18000  # 5 hours.

CELERY_TASK_SERIALIZER = 'msgpack'
CELERY_RESULT_SERIALIZER = 'msgpack'

CELERY_ACCEPT_CONTENT=['msgpack']
CELERY_ENABLE_UTC = True
CELERY_DISABLE_RATE_LIMITS = True